# TODO: Add initialisation for backend and frontend for easier development
services:
  db:
    image: mysql:8.0
    container_name: vrc_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vrc
      MYSQL_USER: vrcuser
      MYSQL_PASSWORD: vrcpassword
    ports:
      - "3306:3306"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.dSE